# -*- coding: utf-8 -*-
"""2.7 example problem

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fiGaWfZmJ_Gmz5DXcHskTS3Ui7Ku9xTy
"""

def main():
  print("This program calculates the future value")
  print("of a 10 year investment")

  principal = eval(input("Enter the initial principal: "))
  apr = eval(input("Enter the annual interest rate: "))

  for i in range(10):
    principal = principal * (1 + apr)

  print("The value in 10 years is:", principal)

main()

