# -*- coding: utf-8 -*-
"""Book Project 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NdgxhSC1480P4YQWlnpo_LyCGkqmimZS

Write a program that determines the distance to a lightning strike based on the time elapsed between the flash and the sound of thunder. The speed of sound is approximately 1100 ft/ sec and 1 mile is 5280 ft.
"""

print("This program will calculate the distance to a lightning strike")
print("Based off the time from the flash and thunder")

def main():
  time = float(input("How long did it take for the sound to reach you(in seconds): "))
  distance = (time * 1100) / 5280
  distance2 = round(distance, 3)
  print("The lightning strike happened", distance2, "miles away")

main()

"""Write a program that calculates the cost per square inch of a circular pizza, given its diameter and price. The formula for area is A = πr2"""

import math
print("Program that will calculate the cost of a circular pizza give the diameter")

def main():
  diameter = float(input("Please enter the diameter of your pizza in inches: "))
  sqrinch = 0.25
  area = math.pi * (diameter / 2) ** 2
  cost = area * sqrinch
  cost2 = round(cost, 2)
  print("The cost of the pizza is $"+ str(cost2),"Dollars.")

main()

"""Write a program to find the sum of the first n natural numbers, where the value of n is provided by the user."""

print("This is a program that will find the sum of natural numbers you provide")

def main():
  n = int(input("How many natural numbers are there: "))
  fact = 1
  for factor in range(n,1,-1):
    fact = fact + factor
  print("The sum of the natural numbers is", fact)

main()

"""A certain CS professor gives 5-point quizzes that are graded on the scale 5-A, 4-B, 3-C, 2-D, 1-F, 0-F. Write a program that accepts a quiz score as an input and prints out the corresponding grade."""

print("Program to convert quiz score to grade")

grades = ['F','F','D','C','B','A']
score = int(input("Please enter your score: "))
grades[score]

"""An acronym is a word formed by taking the first letters of the words in a phrase and making a word from them. For example, RAM is an acronym for "random access memory." Write a program that allows the user to type in a phrase and then outputs the acronym for that phrase. Note : The acronym should be all uppercase, even if the words in the phrase are not capitalized."""

print("A program to make an acronym from a phrase the user provides")

def main():
  phrase = input("Please enter the phrase")
  word_list = phrase.split()

  acronym = ''
  for word in word_list:
    acronym += word[0].upper()

  
  print('\nThe acronym for the phrase',phrase,'is:',acronym + '.')

main()

