# -*- coding: utf-8 -*-
"""Book Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EIioN-VtUeRUEm8hXcvyciGyq-pZVDFY

A user-friendly program should print an introduction that tells the user what the program does. Modify the convert . py program (Section 2.2) to print an introduction.
"""

#convert.py
print("This is a program that will take your input of the tempature in Celsius and then return it to you in Fahrenheit")
def main():
  celsius = eval(input("What is the Celsius temperature? "))
  fahrenheit = 9/5 * celsius + 32
  print("The temperature is", fahrenheit, "degrees Fahrenheit.")
  
main()

"""Modify the avg2. py program (Section 2.5.3) to find the average of three exam scores."""

#avg2.py
#A simple program to average three exam scores
#Illustrates use of multiple input
def main():
  print("This program computes the average of three exam scores.")

  score1, score2, score3 = eval(input("Enter three scores separated by commas."))
  average = (score1 + score2 + score3) / 3
  
  print("The average of the scores is:", average)

main()

"""Modify the futval. py program (Section 2. 7) so that the number of years for the investment is also a user input. Make sure to change the final message to reflect the correct number of years."""

#futval.py
#A program to compute the value of an investment

def main():
  print("This program calculates the future value")
  print("of an investment through your input")

  principal = eval(input("Enter the initial principal: "))
  apr = eval(input("Enter the annual interest rate: "))
  years = eval(input("Enter how many years this will be compounded by"))

  for i in range(years):
    principal = principal * (1 + apr)

  print("The value in", years,"years is:", principal)

main()

"""Write a program that converts temperatures from Fahrenheit to Celsius."""

#A program that converts the tempature
# From Fahrenheit to Celsius

def main():
  fahrenheit = eval(input("What is the Fahrenheit tempature"))
  celsius = (fahrenheit - 32) * 5/9
  print("The temperature is", celsius, "degrees Celsius")

main()

"""Write a program that converts distances measured in kilometers to miles. One kilometer is approximately 0.62 miles."""

#A program that converts distances in kilometers
# to miles through user input

def main():
  print("This program will take kilometers from you and turn it into miles")
  kilometers = eval(input("How many kilometers are there "))
  miles = kilometers * 0.62
  print(kilometers,"kilometers is", miles, "miles")

main()