# -*- coding: utf-8 -*-
"""Copy of Assignment 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QPXA7NaO5WPT-_UQ7KSUF9AY0O-fFolc

Welcome to your first Assignment! Consider this as a worksheet that you will work your way there. There will be times that you need to write some code in the provided area, or explain some code that is already there. Each problem will have a description of what you need to do!

1. Create a variable for a string that is a sentence. Make the whole string uppercase, print the string.
"""

a = "Hello, welcome to Introduction to Programming"
a.upper()

"""2. Create a variable for a string that is a sentence. Make the whole string lowercase, print the string."""

b = "I love to ride my bike, swim, pet my dog Reeses."
b.lower()

"""3. Create a variable for a string that is a sentence. Change the capitilization of a title, print the string."""

c = "My favorite movies are Avengers Endgame, Avengers, and can you see me"
c.title()

"""4. Demonstrate how to use the slice function."""

greet = "Hello Hayden, How are you today?"
print(greet[0:5], greet[6:12])
print(greet[14:])

"""5. Demonstrate how to use the count function on strings."""

len("Hello Hayden")

"""6. Demonstrate how to concatenate two strings"""

first = input("Enter the first word")
second = input("Enter the second word")
#concarenate the first letter with the remaining 5
combined = first[0] + second[0:5]
print(combined)

"""7. Demonstrate how to add integer values into your strings. For example, you get errors when you try to concatenate a number with a string. Demonstrate using a method to overcome this problem."""

myString = "Hello There"
myInt = 4
print(myString + str(myInt))

"""8. Create a list of every letter in the alphabet."""

alphabet = ['a','b','c,','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
print(alphabet)

"""Well done! You finished your fourth worksheet assignment from Google Coloborative. Select File -> Download .py. Take the file that you just downloaded and upload it to Canvas under Assignment 2.2. If you would like you can create a link and just turn in the link by selecting Share in the top right then "Get shareable link" Copy the link and add that to your assignment in canvas."""