# -*- coding: utf-8 -*-
"""Copy of python #1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15m5uqTPTQvx5p_eceH1nh8YWClvwETCC

Welcome to your first Assignment! Consider this as a worksheet that you will work your way there. There will be times that you need to write some code in the provided area, or explain some code that is already there. Each problem will have a description of what you need to do!

1. Describe what is happening in this code and what is being printed
"""

name = "Jim Butcher"
description = "is an American author. He wrote the contemporary fantasy The DresdenFiles, Codex Alera and Cinder Spires book series."
print(name + description)

"""**Answer**: This code is taking a expression for the variable name and description and then the print function is taking those two expressions/strings and printing them out on 1 line.

2. Declare a variable called friends to represent the number of friends you have on a social media. Give it a value. Print out the value by refrencing your constant.
"""

friends = 10
print (friends)

"""3. You have a goal to only eat so many calories everyday. Create a variable dailyCalories and set it to how many calories you are allowed everyday. Then print out a statement that uses your dailyCalories and a sentence describing what you can eat to stay under your goal."""

dailyCalories = 2500
print("Your daily Calorie goal is:",dailyCalories, "You can stay under this goal by eating healthier foods that have less fat and work out to keep in shape.")

"""4. Create a new variable called calories and set it to 0. This variable will store how many calories you eat today. Print calories. Then update the value of calories to how many calories you typically eat for lunch. Print calories again"""

calories = 0
print (calories)
calories = calories + 250
print (calories)

"""5. Imagine you're creating a simple photo sharing app. You want to keep track of the following metrics for each post:

Number of likes: the number of likes that a photo has received

Number of comments: the number of comments other users have left on the photo

Year created: The year the post was created

Month created: The month the post was created represented by a number between 1 and 12

Day created: The day of the month the post was created

For each of the metrics above, declare a variable and assign it a value corresponding to a hypothetical post. Be sure to use proper naming conventions.
"""

likes = 659
comments = 354
year = 2020
month = 8
day = 21

"""6. You decide to build a shed and want to know beforehand the area of your yard that it will take up. Create two variable, width and height, with values of 10 and 20, respectively. Create an area constant that is the result of multiplying the two previous constants together, and print out the result."""

width = 10
height = 20
area = width * height
print(area)

"""7. You decide that you'll divide your shed into two rooms. You want to know if dividing it equally will leave enough room for some of your larger storage items. Create a roomArea variable that is the result of dividing area in half. Print out the result."""

area = 200
roomArea = area / 2
print(roomArea)

"""8. Create a perimeter variable whose value equals width plus width plus height plus height, then print out the result."""

width = 10
height = 20
perimeter = width + width + height + height
print(perimeter)

"""9. Your fitness tracker keeps track of users' heart rate, but you might also want to display their average heart rate over the last hour. Create three variable, heartRate1, heartRate2, and heartRate3. Give each variable a different value between 60 and 100. Create a constant addedHR equal to the sum of all three heart rates. Now create a variable called averageHR that equals addedHR divided by 3 to get the average. Print the result."""

heartRate1 = 60
heartRate2 = 75
heartRate3 = 90
addedHR = heartRate1 + heartRate2 + heartRate3
averageHR = addedHR / 3
print(addedHR)
print(averageHR)

"""10. In addition to heart rate your fitness tracking app tracks distance traveled. Create a variable distance and set it equal to 50. This will represent the user having traveled 50 feet.

You decide, however, to display the distance in meters. 1 meter is approximately equal to 3 feet. Use an to convert distance to meters. Print the result.
"""

distance = 50
meter = 50 / 3

print(meter)

"""Well done! You finished your first worksheet assignment from Google Coloborative. Select File -> Download .py. Take the file that you just downloaded and upload it to Canvas under Assignment 1. If you would like you can create a link and just turn in the link by selecting Share in the top right then "Get shareable link" Copy the link and add that to your assignment in canvas."""