# -*- coding: utf-8 -*-
"""Copy of Assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GH_0Wh2yrnrpKOmEAKiH0T2XrOKC60Mq

Welcome to your first Assignment! Consider this as a worksheet that you will work your way there. There will be times that you need to write some code in the provided area, or explain some code that is already there. Each problem will have a description of what you need to do!

1. Describe what is happening in this code and what is being printed
"""

import math

a= float(input("Enter coefficient a: "))
b= float(input("Enter coefficient b: "))

answer = math.sqrt(math.pow(a,2) + math.pow(b,2))

print(answer)

"""**Answer**:"""

it is taking the user input and turning it into a float number.

"""2. Describe the difference between an integer and a float."""

an integer is 1,2,3,4 no decimal or fraction behind it. 
While float is has a decimal to represent a fraction.

"""3. Have the user input a width and height. Capture the values and compute the area. Area = Width * Height"""

a = float(input("Enter the Width: "))
b = float(input("Enter the Height: "))
area = a * b
print(area)

"""4. Have the user input the width and height of a rectangle. Compute the perimeter. Perimeter = Width + Width + Height + Height"""

width = float(input("Enter the Width: "))
height = float(input("Enter the Height: "))
perimeter = width + width + height + height
print(perimeter)

"""5.  Have the user input a radius. Compute the circumference. Circumference = 2 * pi * Radius"""

import math

raidus = float(input("Enter a radius: "))
circumference = 2 * math.pi * raidus
print(circumference)

"""6. Ask the user to enter three times that they measured their heart rate for the day. Print the average heartrate for them"""

a = float(input("Please enter the first heart rate: "))
b = float(input("Please enter the second heart rate: "))
c = float(input("Please enter the third heart rate: "))
average = (a + b + c) / 3
print(average)

"""7. Ask the user to enter a temperature in Farenheight. Convert to celcius."""

farenheight = float(input("Please enter the Farenheight tempature: "))
celcius = (farenheight - 32) * 5/9
print(farenheight, "degrees Farenheight is", celcius, "degrees celcius")

"""8. Find the average of 1.2, 10.5, 11.6. Round to the nearest whole number."""

average = 1.2 + 10.5 + 11.6
print(int(average))

"""Well done! You finished your second worksheet assignment from Google Coloborative. Select File -> Download .py. Take the file that you just downloaded and upload it to Canvas under Assignment 2.1. If you would like you can create a link and just turn in the link by selecting Share in the top right then "Get shareable link" Copy the link and add that to your assignment in canvas."""