# -*- coding: utf-8 -*-
"""Progress Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YJd2qBt8fOlCG44AwC-K7mQacjFP51XZ
"""

#A program that will calculate the users progress in the course by taking the user input
#and calculating the progress he has made during the course.

def main():
  a = int(input("How many units have you completed: "))
  b = int(input("How many assingments in the current unit have you completed: "))
  c = int(input("How many completed days have you put in the class: "))
  hours = c * 3
  assignments = (a * 5) + b
  progress = (assignments * c) 

  print("The user has put in",hours,"hours in the course")
  print("The users progress is",str(progress) + "%")

main()

